(()=>{'use strict';
const plan=window.STUDY_PLAN, KEY='sap-itc009-study-v1';
let state={version:1,completed:{},notes:{}},selected=plan[0].date,storageOK=true;
const ids=new Set(plan.flatMap(d=>d.tasks.map(t=>t.id)));
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&saved.version===1){for(const [id,val] of Object.entries(saved.completed||{}))if(ids.has(id)&&val===true)state.completed[id]=true;for(const d of plan)if(typeof saved.notes?.[d.date]==='string')state.notes[d.date]=saved.notes[d.date];}}catch{storageOK=false;}
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const linkedDay=new URLSearchParams(location.search).get('day');
selected=plan.find(d=>d.date===linkedDay)?.date||plan.find(d=>d.date===today)?.date||plan[0].date;
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}status();}
function status(){$('storage-status').textContent=storageOK?'勾選與回顧自動儲存在此瀏覽器；不同裝置不會自動同步。':'此瀏覽器目前無法儲存進度；關閉頁面後可能遺失本次勾選與回顧。';}
function count(d){return d.tasks.filter(t=>state.completed[t.id]).length;}
function time(n){return n<60?`${n} 分鐘`:n%60===0?`${n/60} 小時`:`${+(n/60).toFixed(1)} 小時`;}
function dayTime(d){return d.timeLabel||time(d.tasks.reduce((s,t)=>s+(t.minutes||0),0));}
function progress(){const d=plan.find(d=>d.date===selected);$('day-count').textContent=`已完成 ${count(d)} / ${d.tasks.length}`;$('day-progress').value=count(d)/d.tasks.length*100;const core=plan.filter(x=>x.date<='2026-09-19'),all=core.flatMap(x=>x.tasks),done=all.filter(t=>state.completed[t.id]).length;$('overall-count').textContent=`${done} / ${all.length}`;$('overall-progress').value=done/all.length*100;document.querySelectorAll('.nav-day').forEach(el=>{const day=plan.find(x=>x.date===el.dataset.date);el.querySelector('.nav-meta').textContent=`${count(day)} / ${day.tasks.length} 完成 · ${day.date>'2026-09-20'?'課後追蹤':dayTime(day)}`;el.setAttribute('aria-current',day.date===selected?'date':'false');});}
function renderNav(){$('day-nav').innerHTML=plan.map(d=>`<button class="nav-day" data-date="${d.date}" aria-current="${d.date===selected?'date':'false'}"><span class="nav-date">${d.date.slice(5).replace('-','/')}</span><span class="nav-title">${esc(d.label)}<span class="nav-meta"></span></span></button>`).join('');}
function render(){const d=plan.find(d=>d.date===selected);$('day-date').textContent=new Intl.DateTimeFormat('zh-TW',{month:'long',day:'numeric',weekday:'long',timeZone:'UTC'}).format(new Date(d.date+'T12:00:00Z'))+(d.date===today?' · 今天':'');$('day-title').textContent=d.label;$('day-subtitle').textContent=d.subtitle;$('day-time').textContent=dayTime(d);$('day-notice').textContent=d.notice||'';$('tasks').innerHTML=d.tasks.map((t,i)=>`<article class="task ${state.completed[t.id]?'done':''}" data-task="${t.id}"><div class="task-top"><input type="checkbox" id="${t.id}" ${state.completed[t.id]?'checked':''}><label for="${t.id}">${String(i+1).padStart(2,'0')} · ${esc(t.title)}</label><span class="duration">${t.minutes===null?'依當班安排':t.minutes+' 分鐘'}</span></div><div class="task-content"><p class="reading">${window.StudyResources.reading(t.reading,d.date,t.id)}</p><ol>${t.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${t.link?`<p><a href="${esc(t.link.url)}" target="_blank" rel="noopener noreferrer">${esc(t.link.label)} ↗</a></p>`:''}<p class="deliverable"><b>完成條件</b>${esc(t.done)}</p><details><summary>對應筆記</summary>${window.StudyResources.noteList(t.source)}</details>${t.id==='d13-diagnostic'?window.StudyResources.questionSources():''}</div></article>`).join('');$('reflection').value=state.notes[selected]||'';progress();status();}
function setCompleted(id,completed){if(!ids.has(id)||typeof completed!=='boolean')throw new Error('無效的學習任務或完成狀態');if(completed)state.completed[id]=true;else delete state.completed[id];save();render();return {id,completed};}
$('day-nav').addEventListener('click',e=>{const b=e.target.closest('button[data-date]');if(b){selected=b.dataset.date;render();}});
$('tasks').addEventListener('change',e=>{if(e.target.matches('input[type=checkbox]')){const id=e.target.id;setCompleted(id,e.target.checked);$(id)?.focus();}});
$('reflection').addEventListener('input',e=>{state.notes[selected]=e.target.value;save();});
renderNav();render();
const ctx=document.modelContext;
if(ctx?.registerTool){const lifecycle=new AbortController();const registrations=[
{name:'read_study_progress',title:'讀取 SAP 讀書進度',description:'讀取每日學習任務、目前完成狀態與選取日期，不修改進度。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('不接受額外參數');return {selectedDate:selected,days:plan.map(d=>({date:d.date,title:d.label,tasks:d.tasks.map(t=>({id:t.id,title:t.title,completed:!!state.completed[t.id]}))}))};}},
{name:'set_study_task_completion',title:'設定 SAP 任務完成狀態',description:'依使用者回報將指定學習任務勾選或取消，與畫面勾選使用同一份瀏覽器進度。',inputSchema:{type:'object',properties:{taskId:{type:'string'},completed:{type:'boolean'}},required:['taskId','completed'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['taskId','completed'].includes(k))||typeof input.taskId!=='string'||typeof input.completed!=='boolean'||!ids.has(input.taskId))throw new Error('請提供有效任務 ID 與布林完成狀態');selected=plan.find(d=>d.tasks.some(t=>t.id===input.taskId)).date;return {...setCompleted(input.taskId,input.completed),saved:storageOK};}}
];for(const tool of registrations){try{Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',e=>{if(!e.persisted)lifecycle.abort();},{once:true});}
})();
