(()=>{'use strict';
const D=window.SAP_DATA, SINGLE=window.SAP_SINGLE===true, KEY='sap-iphone-progress-v1', $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ids=new Set(D.plan.flatMap(d=>d.tasks.map(t=>t.id))), dates=new Set(D.plan.map(d=>d.date));
const empty=()=>({version:1,daily:{version:1,completed:{},notes:{}},answers:{},marked:{},mock:{},readers:{}});
let state=empty(), storageOK=true, storageError='', registration, cacheBusy=false;
function object(x){return x&&typeof x==='object'&&!Array.isArray(x);}
function validate(input){if(!object(input)||input.version!==1||!object(input.daily)||input.daily.version!==1)throw Error('不支援的進度版本。');
const s=empty(), d=input.daily;if(!object(d.completed)||!object(d.notes))throw Error('每日進度格式錯誤。');
for(const [id,value] of Object.entries(d.completed)){if(!ids.has(id)||typeof value!=='boolean')throw Error('包含未知任務。');if(value)s.daily.completed[id]=true;}
for(const [date,value] of Object.entries(d.notes)){if(!dates.has(date)||typeof value!=='string'||value.length>100000)throw Error('回顧格式錯誤。');s.daily.notes[date]=value;}
for(const key of ['answers','marked','mock','readers'])if(!object(input[key]))throw Error('缺少 '+key+' 進度。');
for(const [id,a] of Object.entries(input.answers)){const q=D.questions.find(q=>q.id===id);if(!q||!object(a)||typeof a.submitted!=='boolean'||!['?',...q.options.map((_,i)=>String.fromCharCode(65+i))].includes(a.choice))throw Error('作答紀錄格式錯誤。');s.answers[id]={choice:a.choice,submitted:a.submitted};}
for(const [id,v] of Object.entries(input.marked)){if(!D.questions.some(q=>q.id===id)||typeof v!=='boolean')throw Error('複習標記格式錯誤。');if(v)s.marked[id]=true;}
for(const [id,a] of Object.entries(input.mock)){if(!D.mock.some(q=>q.id===id)||!object(a)||typeof a.answer!=='string'||a.answer.length>100000||!['','independent','lookup','weak'].includes(a.level))throw Error('模擬評量格式錯誤。');s.mock[id]={answer:a.answer,level:a.level};}
for(const [id,r] of Object.entries(input.readers)){if(!['esr','textbook'].includes(id)||!object(r)||!Number.isInteger(r.page)||r.page<1||r.page>D[id].length||!['both','en','zh'].includes(r.language)||!Number.isInteger(r.font)||r.font<16||r.font>28)throw Error('閱讀位置格式錯誤。');s.readers[id]={page:r.page,language:r.language,font:r.font};}return s;}
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));else{const legacy=JSON.parse(localStorage.getItem('sap-itc009-study-v1')||'null');if(legacy)state=validate({...empty(),daily:legacy});}const probe=KEY+'-probe';localStorage.setItem(probe,'1');localStorage.removeItem(probe);}catch(e){storageOK=false;storageError='已有資料無法讀取或此瀏覽器不允許儲存；請先匯出本次進度。';}
function storageStatus(){$('storage-status').textContent=storageOK?'進度已儲存在此瀏覽器':'⚠ '+(storageError||'儲存失敗；請匯出進度，關閉可能遺失。');$('storage-status').className=storageOK?'':'warning';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;storageError='';}catch{storageOK=false;}storageStatus();}
const card=(title,body)=>`<section class="card"><h2>${title}</h2>${body}</section>`;
const link=(route,text)=>`<a href="#${route}">${esc(text)}</a>`;
const noteLink=name=>link('note?name='+encodeURIComponent(name),name);
function route(){const [page='home',params='']=location.hash.slice(1).split('?');return {page,params:new URLSearchParams(params)};}
function setRoute(page,params={}){location.hash=page+(Object.keys(params).length?'?'+new URLSearchParams(params):'');}
function isWrong(q){const a=state.answers[q.id];return a?.submitted&&q.answer!==null&&a.choice!==q.answer;}
function home(){const done=Object.keys(state.daily.completed).length,answered=D.questions.filter(q=>state.answers[q.id]?.submitted).length;
return `<p class="muted">YOUR OFFLINE STUDY DESK · ${esc(D.built)}</p><h1>準備好，隨時接著讀。</h1><p>保留原有每日安排與教材。${done} / 49 個任務完成 · ${answered} / 89 題已作答 · ${D.questions.filter(isWrong).length} 題需重做。</p><div class="cards">${[['plan','每日學習計畫','13 天 · 49 個任務與每日回顧'],['questions','Pre-course assessment','89 題 · 題圖、選項與中文解析'],['review','錯題複習','本次錯題、手動標記及原 6 題回饋'],['mock','Mock assessment','12 題 · 自編模擬題，非正式考題'],['esr','Electrical Safety Rules','86 頁 · 英文、中文、原圖'],['textbook','HV Textbook','192 頁 · 中英、圖表與掃描'],['notes','研讀筆記','22 份 · 角色、安全文件、隔離與接地']].map(([r,t,s])=>`<a class="card" href="#${r}"><strong>${t}</strong><span class="muted">${s}</span></a>`).join('')}</div>
${card('進度備份與移轉',`<p>每日勾選、回顧、作答、錯題標記、模擬答案與閱讀位置會一起匯出。不同網址、Safari 與主畫面 App 可能各自保存資料。</p><div class="tools"><button data-action="export">匯出全部進度 JSON</button><button data-action="import">匯入進度 JSON</button><button data-action="backup-text">顯示備份文字</button></div><div id="backup-area" hidden><label for="backup-text">備份 JSON（可全選複製，或貼上後匯入）</label><textarea id="backup-text" rows="7"></textarea><button data-action="import-text">匯入上方 JSON</button></div><p class="muted">也可匯入原網站 SAP_Study_Progress 格式，僅替換每日計畫與回顧。</p>`)}
${card('iPhone 離線安裝',`<ol><li>用 Safari 連上本版的 HTTPS 網址，保持畫面開啟，等上方顯示 <b>Offline Ready</b>。</li><li>分享 → 加入主畫面；若有「作為網頁 App 開啟」，保持開啟。</li><li>從新圖示再開一次，連網等到 Offline Ready。</li><li>開飛航模式，另確認 Wi-Fi 已關閉；關閉 App 後重開，測試題目、圖片、筆記與進度。</li></ol><p>單檔 HTML 的內容已內嵌；iPhone「檔案」預覽不保證執行 JavaScript，正式離線入口請使用已安裝 PWA。</p><p class="muted">首次需下載約 ${D.assetMB} MB。iOS 清除網站資料或儲存空間不足可能移除快取，出發前再次實測並匯出 JSON。</p>`)}
${card('教材範圍與來源',`<p>PTW / SFT / LOA、AP / SAP / CP / Safety Person、HV switching / isolation / proving dead / earthing 均可在 ESR、Textbook 及筆記中搜尋。</p><p>來源圖像已製作手機閱讀副本；原始檔未改動。教材內引用的外部網站以書目文字保留，離線功能不依賴它們。影片與未在既有網站提供的原始 HEIC / PDF 不屬於此閱讀包。</p><p>題庫 Q38 不自動判分；Q75 保留單位疑義。${link('references','課前評估完整來源與版本說明')}</p><p class="muted">ESR 修訂 ${esc(D.esrRevision)} · Textbook 修訂 ${esc(D.textbookRevision)} · build ${esc(D.build)}</p>`)} `;}
function planView(params){const d=D.plan.find(d=>d.date===params.get('day'))||D.plan[0],n=d.tasks.filter(t=>state.daily.completed[t.id]).length;
return `<h1>每日學習計畫</h1><label>選擇日期 <select id="study-day">${D.plan.map(x=>`<option value="${x.date}" ${x===d?'selected':''}>${x.date} · ${esc(x.label)}</option>`).join('')}</select></label><h2>${esc(d.label)}</h2><p>${esc(d.subtitle)}</p><p class="notice">${esc(d.notice||d.timeLabel||'依原計畫安排；課內順序依講師。')}</p><p>${n} / ${d.tasks.length} 完成</p><progress value="${n}" max="${d.tasks.length}" aria-label="當日完成任務"></progress>${d.tasks.map(t=>`<article class="card ${state.daily.completed[t.id]?'complete':''}"><label class="task-label"><input type="checkbox" data-task="${t.id}" ${state.daily.completed[t.id]?'checked':''}>${esc(t.title)}</label><p class="muted">${t.minutes==null?'依當班安排':t.minutes+' 分鐘'} · ${esc(t.reading)}</p><ol>${t.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p><b>完成條件：</b>${esc(t.done)}</p><details><summary>對應筆記與教材</summary><ul>${t.source.split('；').map(n=>`<li>${noteLink(n)}</li>`).join('')}</ul><p>${link('esr','ESR 閱讀器')} · ${link('textbook','Textbook 閱讀器')}</p>${t.link?`<p class="muted">原計畫外部參考（需連網，僅保留書目）：${esc(t.link.label)} ${esc(t.link.url)}</p>`:''}</details></article>`).join('')}<section class="card"><label for="reflection">${d.date} 今日回顧</label><textarea id="reflection" data-date="${d.date}">${esc(state.daily.notes[d.date]||'')}</textarea></section>`;}
function quizView(params,review=false){const query=params.get('search')||'',filter=params.get('filter')||(review?'wrong':'all');let matches=D.questions.filter(q=>(!query||(q.search+' '+q.id).toLowerCase().includes(query.toLowerCase()))&&(filter==='all'||filter==='wrong'&&isWrong(q)||filter==='marked'&&state.marked[q.id]||filter==='historical'&&q.historical||filter==='uncertain'&&q.answer===null));const q=matches.find(q=>q.id===params.get('id'))||matches[0];
const toolbar=`<form id="quiz-search" class="tools"><input name="search" type="search" value="${esc(query)}" placeholder="搜尋題號、英文、中文" aria-label="搜尋題庫"><select name="filter" aria-label="題庫篩選">${[['all','全部 89 題'],['wrong','本次作答錯題'],['marked','我標記的複習題'],['historical','2026/9/17 原 6 題錯題'],['uncertain','待確認，不計分']].map(([v,t])=>`<option value="${v}" ${v===filter?'selected':''}>${t}</option>`).join('')}</select><button>搜尋／篩選</button></form>`;
if(!q)return `<h1>${review?'錯題複習':'課前評估／題庫'}</h1>${toolbar}<p>目前沒有符合條件的題目。可改選「全部 89 題」或原 6 題回饋。</p>`;
const a=state.answers[q.id],i=matches.indexOf(q),submitted=a?.submitted;
return `<h1>${review?'錯題複習':'HV AP Pre-course Assessment'}</h1><p class="muted">研讀整理版，非完整官方答案鍵。Q38 待確認、不自動判分；其他題目依原研讀判讀及六題正式回饋。${link('references','來源與限制')}</p>${toolbar}<div class="tools"><button data-action="question" data-id="${matches[i-1]?.id||''}" ${i===0?'disabled':''}>上一題</button><select id="question-jump" aria-label="選擇題號">${matches.map(x=>`<option value="${x.id}" ${x===q?'selected':''}>${x.id.toUpperCase()} · ${esc(x.title.slice(0,42))}</option>`).join('')}</select><button data-action="question" data-id="${matches[i+1]?.id||''}" ${i===matches.length-1?'disabled':''}>下一題</button></div><p class="muted">第 ${i+1} / ${matches.length} 題</p><article class="card" id="question-card">${q.prompt}<fieldset><legend>選擇你的答案</legend>${[...q.options,'Don’t know'].map((x,n)=>{const value=n===q.options.length?'?':String.fromCharCode(65+n);return `<label class="answer-choice"><input type="radio" name="choice" data-q="${q.id}" value="${value}" ${a?.choice===value?'checked':''}> <span>${value==='?'?'—':value+'.'} ${x}</span></label>`;}).join('')}</fieldset><div class="tools"><button data-action="submit-answer" data-id="${q.id}">核對答案</button><label><input type="checkbox" data-mark="${q.id}" ${state.marked[q.id]?'checked':''}>加入複習</label></div>${submitted?`<p class="result">${q.answer===null?'此題待確認，不計分。':a.choice===q.answer?'與研讀版參考答案一致。':'與研讀版參考答案不同；已列入本次錯題。'} 你的選擇：${esc(a.choice)}</p>`:''}<details ${submitted?'open':''}><summary>查看原有答案與中文解析</summary>${q.solution}</details></article>`;}
function mockView(){return `<h1>Mock assessment · 12 題</h1><p class="notice">自編模擬題，非正式考題。建議 50 分鐘，沒有官方及格線；先寫自己的答案，再看參考判讀。</p><p>依原有 11_Mock_Assessment.md 保留題幹、來源與判讀。${noteLink('11_Mock_Assessment.md')}</p>${D.mock.map(q=>`<article class="card"><h2>${esc(q.title)}</h2><div>${q.prompt}</div><label for="mock-${q.id}">我的回答與待確認事項</label><textarea id="mock-${q.id}" data-mock="${q.id}">${esc(state.mock[q.id]?.answer||'')}</textarea><label>自我診斷 <select data-mock-level="${q.id}">${[['','尚未評估'],['independent','能獨立解釋'],['lookup','查頁後理解'],['weak','仍需補強']].map(([v,t])=>`<option value="${v}" ${state.mock[q.id]?.level===v?'selected':''}>${t}</option>`).join('')}</select></label><details><summary>參考判讀（先作答）</summary>${q.answer}</details></article>`).join('')}`;}
function readerView(type,params){const pages=D[type],saved=state.readers[type]||{page:1,language:'both',font:18},query=params.get('search')||'',matches=pages.filter(p=>!query||(p.title+' '+p.en+' '+p.zh).toLowerCase().includes(query.toLowerCase())),page=+(params.get('page')||saved.page),p=matches.find(p=>p.page===page)||matches[0];if(!p)return `<h1>${type==='esr'?'ESR':'Textbook'}</h1>${readerSearch(type,query)}<p>沒有符合的頁面。${link(type,'返回全書')}</p>`;
state.readers[type]={...saved,page:p.page};save();const i=matches.indexOf(p);
return `<h1>${type==='esr'?'ESR · Electrical Safety Rules':'HV Textbook'}</h1>${readerSearch(type,query)}<div class="tools"><button data-action="reader-page" data-page="${matches[i-1]?.page||''}" ${i===0?'disabled':''}>上一頁</button><select id="reader-jump" aria-label="選擇教材頁碼">${matches.map(x=>`<option value="${x.page}" ${x===p?'selected':''}>${x.page} · ${esc(x.title.slice(0,45))}</option>`).join('')}</select><button data-action="reader-page" data-page="${matches[i+1]?.page||''}" ${i===matches.length-1?'disabled':''}>下一頁</button></div><div class="tools"><label>語言 <select id="reader-language">${[['both','中英對照'],['en','English'],['zh','繁體中文']].map(([v,t])=>`<option value="${v}" ${saved.language===v?'selected':''}>${t}</option>`).join('')}</select></label><label>字級 <select id="reader-font">${[16,18,20,24,28].map(n=>`<option ${saved.font===n?'selected':''}>${n}</option>`).join('')}</select></label><span class="muted">${matches.length} / ${pages.length} 頁</span></div><article class="card"><p class="muted">${type==='esr'?'ESR 印刷頁':'Textbook PDF 實體頁'} ${p.page}${type==='textbook'&&p.page>2?' · 印刷頁 '+(p.page-2):''}</p><h2>${esc(p.title)}</h2><p class="notice">${esc(p.notice||'中文為 AI 學習譯文；依英文及掃描核對。')}</p><div class="reader-text ${saved.language==='both'?'bilingual':''}" style="--reader-font:${saved.font}px">${saved.language!=='zh'?`<section lang="en"><h3>English</h3><div class="text">${esc(p.en)}</div></section>`:''}${saved.language!=='en'?`<section><h3>繁體中文</h3><div class="text">${esc(p.zh)}</div></section>`:''}</div>${(p.figures||[]).map(f=>`<figure><img loading="lazy" src="${esc(f.src)}" alt="${esc(f.caption)}"><figcaption>${esc(f.caption)}</figcaption></figure>`).join('')}<details id="scan-details"><summary>原頁掃描（手機閱讀副本，可雙指放大）</summary><img class="scan" loading="lazy" src="${esc(p.scan)}" alt="${type} 第 ${p.page} 頁來源掃描"></details><p class="source">${esc(p.source)}</p></article>`;}
function readerSearch(type,q){return `<form id="reader-search" class="tools"><input name="search" type="search" value="${esc(q)}" aria-label="搜尋教材" placeholder="搜尋 PTW、Safety Person、earthing…"><button>搜尋全書</button><a href="#${type}">清除搜尋</a></form>`;}
function notesView(params){const query=params.get('search')||'';return `<h1>研讀筆記</h1><form id="notes-search" class="tools"><input name="search" type="search" value="${esc(query)}" aria-label="搜尋筆記" placeholder="角色、安全文件、OIEC、isolation…"><button>搜尋</button></form>${D.notes.filter(n=>!query||(n.name+' '+n.text).toLowerCase().includes(query.toLowerCase())).map(n=>card(esc(n.title),`<p>${noteLink(n.name)}</p>`)).join('')}`;}
function render(){const {page,params}=route();document.querySelectorAll('nav a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+page?'page':'false'));const views={home,plan:()=>planView(params),questions:()=>quizView(params),review:()=>quizView(params,true),mock:mockView,esr:()=>readerView('esr',params),textbook:()=>readerView('textbook',params),notes:()=>notesView(params),note:()=>{const n=D.notes.find(n=>n.name===params.get('name'));return n?`<p>${link('notes','← 全部筆記')}</p><article class="card note-body">${n.html}</article>`:'找不到指定筆記。';},references:()=>`<h1>課前評估來源與版本</h1><div class="card refs">${D.references}</div>`};$('main').innerHTML=(views[page]||home)();storageStatus();}
function backup(){return {format:'SAP_Offline_Progress',version:1,exportedAt:new Date().toISOString(),build:D.build,state};}
async function exportBackup(){const text=JSON.stringify(backup(),null,2),file=new File([text],'SAP_Progress_'+new Date().toISOString().slice(0,10)+'.json',{type:'application/json'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'SAP 學習進度'});return;}catch(e){if(e.name==='AbortError')return;}}const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function importBackup(text){if(text.length>8*1024*1024)throw Error('備份超過 8 MB。');const b=JSON.parse(text);let next;if(b.format==='SAP_Study_Progress'&&b.version===1)next=validate({...state,daily:b.state});else if(b.format==='SAP_Offline_Progress'&&b.version===1)next=validate(b.state);else throw Error('不是 SAP 進度備份。');if(!confirm('匯入會替換備份涵蓋的進度。若尚未備份目前進度，請取消並先匯出。確定匯入？'))return;try{localStorage.setItem(KEY,JSON.stringify(next));}catch{throw Error('瀏覽器無法儲存，未套用匯入。請先允許網站儲存或釋放空間。');}state=next;storageOK=true;storageError='';render();alert('進度已匯入並儲存。');}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,r=route();try{
if(action==='export')await exportBackup();if(action==='import')$('import-file').click();if(action==='backup-text'){$('backup-area').hidden=false;$('backup-text').value=JSON.stringify(backup(),null,2);}if(action==='import-text')importBackup($('backup-text').value);
if(action==='question'){r.params.set('id',b.dataset.id);setRoute(r.page,Object.fromEntries(r.params));}
if(action==='submit-answer'){const id=b.dataset.id;if(!state.answers[id]){alert('請先選擇答案。');return;}state.answers[id].submitted=true;save();render();}
if(action==='reader-page'){r.params.set('page',b.dataset.page);setRoute(r.page,Object.fromEntries(r.params));}
}catch(error){alert(error.message);}});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='reflection'){state.daily.notes[t.dataset.date]=t.value;save();}if(t.dataset.mock){const id=t.dataset.mock;state.mock[id]={answer:t.value,level:state.mock[id]?.level||''};save();}});
document.addEventListener('change',e=>{const t=e.target,r=route();if(t.dataset.task){if(t.checked)state.daily.completed[t.dataset.task]=true;else delete state.daily.completed[t.dataset.task];save();render();}if(t.id==='study-day')setRoute('plan',{day:t.value});if(t.dataset.q){state.answers[t.dataset.q]={choice:t.value,submitted:false};save();const result=$('question-card')?.querySelector('.result');if(result)result.remove();const details=$('question-card')?.querySelector('details');if(details)details.open=false;}if(t.dataset.mark){if(t.checked)state.marked[t.dataset.mark]=true;else delete state.marked[t.dataset.mark];save();}if(t.id==='question-jump'){r.params.set('id',t.value);setRoute(r.page,Object.fromEntries(r.params));}if(t.dataset.mockLevel){const id=t.dataset.mockLevel;state.mock[id]={answer:state.mock[id]?.answer||'',level:t.value};save();}if(t.id==='reader-jump'){r.params.set('page',t.value);setRoute(r.page,Object.fromEntries(r.params));}if(t.id==='reader-language'||t.id==='reader-font'){state.readers[r.page][t.id==='reader-font'?'font':'language']=t.id==='reader-font'?+t.value:t.value;save();render();}});
document.addEventListener('submit',e=>{if(!['quiz-search','reader-search','notes-search'].includes(e.target.id))return;e.preventDefault();const p=Object.fromEntries(new FormData(e.target));setRoute(route().page,p);});
$('import-file').addEventListener('change',async()=>{try{const f=$('import-file').files[0];if(f){if(f.size>8*1024*1024)throw Error('備份超過 8 MB。');importBackup(await f.text());}}catch(error){alert('未匯入：'+error.message);}finally{$('import-file').value='';}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{state=validate(JSON.parse(e.newValue));render();}catch{}}});
function offlineText(text,ready=false){$('offline-status').textContent=text;$('offline-status').className=ready?'ready':'warning';}
function checkCache(){if(!navigator.serviceWorker?.controller)return;const channel=new MessageChannel();const timeout=setTimeout(()=>{offlineText('無法確認離線快取；請重新檢查。');$('cache-retry').hidden=false;},15000);channel.port1.onmessage=e=>{clearTimeout(timeout);channel.port1.close();const s=e.data;if(s.build!==D.build){offlineText('新版已準備，請重新開啟頁面。');$('update-app').hidden=false;return;}offlineText(s.ready?`Offline Ready · ${s.total} 個檔案已備妥${navigator.onLine?'':' · 目前離線'}`:`離線資料不完整（${s.count}/${s.total}），請連網後重新準備。`,s.ready);$('cache-retry').hidden=s.ready;};navigator.serviceWorker.controller.postMessage({type:'STATUS'},[channel.port2]);}
async function register(){if(SINGLE){offlineText('Offline Ready · 單檔內容與圖片已內嵌',true);return;}if(!('serviceWorker'in navigator)||!isSecureContext||!/^https?:$/.test(location.protocol)){offlineText('PWA 需以 HTTPS 開啟並完成離線下載；也可使用單檔備用版。');return;}try{registration=await navigator.serviceWorker.register('sw.js',{scope:'./',updateViaCache:'none'});function waiting(){if(registration.waiting){$('update-app').hidden=false;offlineText('新版已完整下載；按「套用新版」更新。');}}registration.addEventListener('updatefound',()=>{const w=registration.installing;w?.addEventListener('statechange',()=>{waiting();if(w.state==='redundant'){offlineText('離線下載失敗，請保持連網重試。');$('cache-retry').hidden=false;}});});waiting();if(navigator.serviceWorker.controller)checkCache();else offlineText('首次離線資料下載中，請保持畫面開啟…');navigator.serviceWorker.ready.then(()=>checkCache());}catch(e){offlineText('無法啟用離線快取：'+e.message);$('cache-retry').hidden=false;}}
if(!SINGLE&&'serviceWorker'in navigator){navigator.serviceWorker.addEventListener('message',e=>{const m=e.data;if(m.type==='CACHE_PROGRESS')offlineText(`準備離線資料：${m.count}/${m.total}，請勿關閉畫面…`);if(m.type==='CACHE_ERROR'){offlineText('離線下載未完成：'+m.message);$('cache-retry').hidden=false;}if(m.type==='CACHE_STATUS'&&navigator.serviceWorker.controller)checkCache();});navigator.serviceWorker.addEventListener('controllerchange',()=>checkCache());}
$('cache-retry').onclick=async()=>{if(navigator.serviceWorker?.controller)navigator.serviceWorker.controller.postMessage({type:'PREPARE'});else await register();};
$('update-app').onclick=()=>{save();if(registration?.waiting){navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});registration.waiting.postMessage({type:'ACTIVATE'});}else location.reload();};
for(const event of ['online','offline','pageshow'])window.addEventListener(event,()=>{if(!SINGLE)checkCache();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!SINGLE)checkCache();});
render();register();
})();
