(()=>{'use strict';
const $=id=>document.getElementById(id),data=window.TEXTBOOK_DATA;
if(!data?.pages?.length){$('page-title').textContent='教材資料尚未載入';return;}
const all=data.pages, refs=window.TextbookReferences,plan=window.STUDY_PLAN,params=new URLSearchParams(location.search),key='sap-textbook-reader-v1';
let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{}
let language=['en','zh','both'].includes(saved.language)?saved.language:'both',view=['text','split','image'].includes(saved.view)?saved.view:'text',font=Math.min(28,Math.max(14,+saved.font||18));
let selectedDay=plan.some(d=>d.date===params.get('day'))?params.get('day'):'',taskId=params.get('task')||'',explicit=refs.parse(params.get('pages')||''),query='',current=1;
const dayPages=refs.pagesForDay;
function allowed(){if(explicit.length)return explicit;if(selectedDay)return dayPages(plan.find(d=>d.date===selectedDay));return all.map(p=>p.page);}
function save(){try{localStorage.setItem(key,JSON.stringify({page:current,language,view,font}));}catch{}}
function node(tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;}
function highlighted(text){const fragment=document.createDocumentFragment();if(!query){fragment.append(document.createTextNode(text));return fragment;}const lower=text.toLowerCase(),needle=query.toLowerCase();let start=0,pos=lower.indexOf(needle);while(pos>=0){fragment.append(document.createTextNode(text.slice(start,pos)),node('mark',text.slice(pos,pos+query.length)));start=pos+query.length;pos=lower.indexOf(needle,start);}fragment.append(document.createTextNode(text.slice(start)));return fragment;}
function hashPage(){const m=location.hash.match(/^#page-(\d{3})$/);return m?+m[1]:0;}
function updateUrl(){const q=new URLSearchParams();if(explicit.length)q.set('pages',explicit.join(','));if(selectedDay)q.set('day',selectedDay);if(taskId)q.set('task',taskId);history.replaceState(null,'',location.pathname+(q.size?'?'+q:'')+'#page-'+String(current).padStart(3,'0'));}
function renderList(){const range=allowed(),matches=all.filter(p=>range.includes(p.page)&&(!query||(p.title+'\n'+p.english+'\n'+p.zh).toLowerCase().includes(query.toLowerCase())));$('pages').replaceChildren(...matches.map(p=>{const a=node('a','');a.href='#page-'+String(p.page).padStart(3,'0');a.dataset.page=p.page;if(p.page===current)a.setAttribute('aria-current','page');a.append(node('span',String(p.page).padStart(3,'0'),'number'));const t=node('span','');t.append(highlighted(p.title));a.append(t);return a;}));if(!matches.length)$('pages').append(node('p','此範圍沒有符合的頁面；可清除搜尋或選擇全書。'));$('search-status').textContent=query?`搜尋結果 ${matches.length}／${range.length} 頁`:`本次範圍 ${range.length} 頁 · PDF 頁碼`;$('jump').replaceChildren(...range.map(n=>{const o=node('option',`PDF ${n} / 印刷 ${n>2?n-2:'無'}`);o.value=n;return o;}));$('jump').value=current;const active=$('pages').querySelector('[aria-current]');if(active){const nav=$('pages'),r=active.getBoundingClientRect(),box=nav.getBoundingClientRect();if(matchMedia('(max-width:700px)').matches){nav.scrollLeft+=r.left-box.left;}else if(r.top<box.top||r.bottom>box.bottom){nav.scrollTop+=r.top-box.top;}}}
function paragraphColumn(text,label,lang){const col=node('section','',`lang-col ${lang}`);col.lang=lang==='en'?'en':'zh-Hant';col.append(node('h3',label));const paragraph=para=>{const p=node('p','');p.append(highlighted(para));return p;};if(window.TextbookFigures)window.TextbookFigures.append(col,text,lang,all[current-1].images,paragraph);else for(const para of text.split(/\n\s*\n/))col.append(paragraph(para));return col;}
function render({scroll=true,url=true}={}){const p=all[current-1],range=allowed();$('page-label').textContent=`PDF 第 ${p.page}／192 頁 · ${p.page>2?'原書印刷第 '+(p.page-2)+' 頁':'封面／版權頁'}`;$('page-title').textContent=p.title;$('notes').textContent=(p.notes||[]).join('\n');$('language').value=language;$('view').value=view;document.documentElement.style.setProperty('--text',font+'px');$('smaller').disabled=font<=14;$('larger').disabled=font>=28;$('reading').className='view-'+view;const content=node('div','',language==='both'?'bilingual':'');if(language!=='zh')content.append(paragraphColumn(p.english,p.englishMethod==='local-edited'?'ENGLISH · 已儲存修正':p.englishMethod==='scan-reviewed'?'ENGLISH · 掃描核對轉錄':'ENGLISH · OCR', 'en'));if(language!=='en')content.append(paragraphColumn(p.zh||'本頁尚待翻譯。','繁體中文 · 學習譯文','zh'));$('text').replaceChildren(content);$('image').hidden=false;$('image-error').hidden=true;const image=`images/page-${String(current).padStart(3,'0')}.webp`;$('image').src=image;$('image').alt=`原始 Textbook.PDF 第 ${current} 頁掃描閱讀副本`;$('full-image').href=image;$('image-link').href=image;$('source').textContent=`英文來源：${p.englishMethod==='local-edited'?'已儲存的英文修正':p.englishMethod==='scan-reviewed'?'OCR／掃描核對轉錄':'Textbook_OCR.pdf'}，PDF p${current}｜掃描：Textbook.PDF，同頁。中文為 AI 學習翻譯；未經全書人工逐字複核。`;$('prev').disabled=range.indexOf(current)<=0;$('next').disabled=range.indexOf(current)===range.length-1;const d=plan.find(d=>d.date===selectedDay),task=d?.tasks.find(t=>t.id===taskId);$('task-context').textContent=task?`${d.date} · ${task.title}｜${task.reading}`:d?`${d.date} · ${d.label}｜依當日 Textbook 指定頁數閱讀`:'全書中英對照 · OCR 不清楚時，切換「文字＋掃描」核對';const printed=range.filter(n=>n>2).map(n=>n-2),scope=explicit.length?'本次任務範圍':selectedDay?'當日 Textbook 範圍':'全書範圍';$('range-label').textContent=`${scope}：${range.length} 頁\nPDF：${refs.formatPages(range)}\n課本印刷：${printed.length?refs.formatPages(printed):'無'}${range.some(n=>n<=2)?'（另含封面／版權頁）':''}`;$('day-all').hidden=!explicit.length||!d||!dayPages(d).length;if(d)$('day-all').textContent=`閱讀當日全部 Textbook（${dayPages(d).length} 頁）`;$('back').href='../index.html'+(selectedDay?'?day='+selectedDay:'');document.title=`Textbook PDF ${current} · ${p.title}`;renderList();if(url)updateUrl();if(scroll)$('scroll').scrollTop=0;save();}
function go(n){if(!allowed().includes(n))return;current=n;render();}
for(const d of plan){const pages=dayPages(d);if(!pages.length)continue;const opt=node('option',`${d.date.slice(5)} · ${d.label}（${pages.length} 頁）`);opt.value=d.date;$('day').append(opt);}
$('day-all').addEventListener('click',()=>{explicit=[];taskId='';if(!allowed().includes(current))current=allowed()[0];query='';$('search').value='';render();});
$('day').value=selectedDay;
const target=hashPage()||Number(saved.page)||allowed()[0];current=allowed().includes(target)?target:allowed()[0];
$('day').addEventListener('change',()=>{selectedDay=$('day').value;explicit=[];taskId='';current=allowed()[0];query='';$('search').value='';render();});
$('pages').addEventListener('click',e=>{const a=e.target.closest('a[data-page]');if(a){e.preventDefault();go(+a.dataset.page);}});
$('prev').addEventListener('click',()=>go(allowed()[allowed().indexOf(current)-1]));$('next').addEventListener('click',()=>go(allowed()[allowed().indexOf(current)+1]));$('jump').addEventListener('change',()=>go(+$('jump').value));
$('language').addEventListener('change',()=>{language=$('language').value;render({scroll:false});});$('view').addEventListener('change',()=>{view=$('view').value;render({scroll:false});});
$('smaller').addEventListener('click',()=>{font=Math.max(14,font-1);render({scroll:false});});$('larger').addEventListener('click',()=>{font=Math.min(28,font+1);render({scroll:false});});
$('search').addEventListener('input',()=>{query=$('search').value.trim();render({scroll:false,url:false});});
$('image').addEventListener('error',()=>{$('image').hidden=true;$('image-error').hidden=false;});
window.addEventListener('hashchange',()=>{const n=hashPage();if(allowed().includes(n)){current=n;render({url:false});}});
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||e.target.closest('input,textarea,select,button,a,dialog,[contenteditable]'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();go(allowed()[allowed().indexOf(current)+(e.key==='ArrowRight'?1:-1)]);}});
$('download-page').addEventListener('click',()=>{const p=all[current-1];const text=`# Textbook PDF p${current}｜${p.title}\n\n> 學習用途，不可直接作為現場操作指令。\n\n`+(language!=='zh'?`## ${p.englishMethod==='local-edited'?'English — saved correction':p.englishMethod==='scan-reviewed'?'English — OCR / scan transcription':'English OCR'}\n\n${p.english}\n\n`:'')+(language!=='en'?`## 繁體中文學習譯文\n\n${p.zh}\n\n`:'')+`來源：Textbook_OCR.pdf／Textbook.PDF，PDF p${current}。\n\n${(p.notes||[]).join('\n')}`+(window.TextbookFigures?.markdown(p.images)||'');const u=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'})),a=node('a','');a.href=u;a.download=`Textbook_p${String(current).padStart(3,'0')}_${language}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
render({scroll:false});
})();
